import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}></body>

      <div class="flex bg-slate-950 min-h-screen text-white max-w-[1500px] mx-auto">
        <aside class="hidden sm:flex flex-col items-center xl:items-start xl:w-[340px] p3 fixed h-full">
          <div class="flex items-center w-14 h-14 hoverAnimation p-0 xl:ml-24">
            <img alt="The project logo" src={IconFlames} />
          </div>
          <div class="space-y-3 mt-3 mb-3 xl:ml-24">
            <p>Nav Item</p>
            <p>Nav Item</p>
            <p>Nav Item</p>
          </div>
        </aside>
        <main class="">{children}</main>
        <aside class="widgets">Widgets</aside>
      </div>
      <footer class="">Footer</footer>
    </html>
  );
}
